#!/usr/bin/env python3
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import os
import sys

# --- Config ---
CSV = "species_by_month_counts.csv"
IMAGE_MAP_CSV = "species_image_map.csv"
NATIVE_LIST_FILE = "sf_natives_from_pdf.csv"   # file generated by your pdf-table extraction (one genus species per line, no header)
OUT_HTML = "plotly_bloom_heatmap.html"
MIN_TOTAL = 1
MONTH_COLS = [str(i) for i in range(1, 13)]
META_COLS = ['scientific_name', 'taxon_id', 'common_name']
ROW_HEIGHT = 100  # pixels per row
PLACEHOLDER = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAE0lEQVR42mP8z/C/HwAIkQO2q3n5WwAAAABJRU5ErkJggg=="

# --- Load data ---
if not os.path.exists(CSV):
    print(f"ERROR: counts CSV not found: {CSV}")
    sys.exit(1)

df = pd.read_csv(CSV, dtype=str, low_memory=False)

# ensure month columns exist and are numeric
for m in MONTH_COLS:
    if m not in df.columns:
        raise SystemExit(f"Missing month column '{m}' in {CSV}")

# convert month columns to numeric (zeros for non-parsable)
for m in MONTH_COLS:
    df[m] = pd.to_numeric(df[m], errors='coerce').fillna(0).astype(int)

# keep meta columns (if missing, create blank)
for meta in META_COLS:
    if meta not in df.columns:
        df[meta] = ""

counts = df[MONTH_COLS].copy()
for meta in META_COLS:
    counts[meta] = df[meta]

# Filter species by total observations
counts['total'] = counts[MONTH_COLS].sum(axis=1)
counts = counts[counts['total'] >= MIN_TOTAL].drop(columns=['total'])

# Build genus_species column from scientific_name (first two tokens)
def to_genus_species(s):
    if pd.isna(s):
        return ""
    toks = str(s).split()
    if len(toks) >= 2:
        return f"{toks[0]} {toks[1]}"
    return str(s).strip()

counts['genus_species'] = counts['scientific_name'].apply(to_genus_species)

# --- Load native list (handle headerless single-column CSV or plain text) ---
native_set = set()
if os.path.exists(NATIVE_LIST_FILE):
    try:
        # try reading as a single-column CSV (no header)
        tmp = pd.read_csv(NATIVE_LIST_FILE, header=None, dtype=str)
        # flatten to strings and normalize
        for v in tmp.iloc[:, 0].astype(str).fillna("").tolist():
            v = v.strip()
            if not v:
                continue
            # if CSV had a header "genus_species" accidentally, skip it
            if v.lower() in ("genus_species", "scientific_name", "scientific name"):
                continue
            # keep only first two tokens to normalize (user requested genus+species)
            toks = v.split()
            if len(toks) >= 2:
                native_set.add(f"{toks[0]} {toks[1]}")
            else:
                native_set.add(v)
    except Exception:
        # fallback to simple line-by-line read
        with open(NATIVE_LIST_FILE, "r", encoding="utf-8") as f:
            for line in f:
                v = line.strip()
                if not v:
                    continue
                if v.lower() in ("genus_species", "scientific_name", "scientific name"):
                    continue
                toks = v.split()
                if len(toks) >= 2:
                    native_set.add(f"{toks[0]} {toks[1]}")
                else:
                    native_set.add(v)
else:
    raise SystemExit(f"Native list file not found: {NATIVE_LIST_FILE}")

print(f"Loaded {len(native_set)} native genus+species from {NATIVE_LIST_FILE}")

# --- Filter counts by native_set matching genus_species ---
pre_filter_count = len(counts)
counts = counts[counts['genus_species'].isin(native_set)].copy()
post_filter_count = len(counts)
print(f"Filtered counts: {pre_filter_count} -> {post_filter_count} rows (after native list)")

if post_filter_count == 0:
    print("ERROR: No species left after filtering by native list. Check NATIVE_LIST_FILE and CSV genus/species matching.")
    sys.exit(1)

# Row-normalize
normalized = counts[MONTH_COLS].div(counts[MONTH_COLS].max(axis=1), axis=0).fillna(0)

# --- Determine most prevalent month and order ---
max_month_idx = counts[MONTH_COLS].idxmax(axis=1)
max_month = max_month_idx.astype(int)
ordered_idx = max_month.sort_values().index
ordered_normalized = normalized.loc[ordered_idx]

# Y-axis labels (common name)
y_labels = counts.loc[ordered_idx].apply(lambda r: r['common_name'] if r['common_name'] else r['scientific_name'], axis=1)

# --- Load image map ---
image_map = {}
if os.path.exists(IMAGE_MAP_CSV):
    try:
        imdf = pd.read_csv(IMAGE_MAP_CSV, dtype=str)
        if 'species' in imdf.columns and 'image_url' in imdf.columns:
            image_map = dict(zip(imdf['species'].astype(str), imdf['image_url'].astype(str)))
    except Exception:
        print("Warning: couldn't read IMAGE_MAP_CSV; continuing without images.")

# --- Prepare hover text ---
hover_text = []
for i_row, sp in enumerate(ordered_normalized.index):
    sci_name = counts.loc[sp, 'scientific_name']
    common_name = counts.loc[sp, 'common_name']
    img_url = image_map.get(to_genus_species(sci_name) or sci_name, PLACEHOLDER)
    for i_col, month in enumerate(MONTH_COLS):
        rel = ordered_normalized.iloc[i_row, i_col]
        raw_count = counts.loc[sp, month]
        hover_html = f"<b>{sci_name}</b> ({common_name})<br>Month: {month}<br>Relative prevalence: {rel:.2f}<br>Obs: {raw_count}<br>{img_url}"
        hover_text.append(hover_html)
hover_text = np.array(hover_text).reshape(ordered_normalized.shape)

# --- Heatmap ---
heat = go.Heatmap(
    z=ordered_normalized.values,
    x=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
    y=y_labels,
    colorscale="Viridis",
    zmin=0,
    zmax=1,
    hoverinfo="text",
    text=hover_text,
    showscale=False  # remove colorbar
)

# --- Layout images on the right ---
layout_images = []
for sp, y_label in zip(counts.loc[ordered_idx]['scientific_name'], y_labels):
    # image_map keys are expected to be genus_species or scientific_name depending on your image map
    gs = to_genus_species(sp)
    src = image_map.get(gs, image_map.get(sp, PLACEHOLDER))
    layout_images.append(dict(
        source=src,
        xref="paper",
        yref="y",
        x=1.02,          # right of heatmap
        y=y_label,
        sizex=0.14,
        sizey=1.0,
        xanchor="left",
        yanchor="middle",
        layer="above",
        sizing="contain",
    ))

# --- Build figure ---
fig = go.Figure(data=[heat])

fig.update_layout(
    title="SF Native Plants — Monthly Relative Prevalence (filtered to SF natives)",
    width=1200,
    height=max(600, ROW_HEIGHT * len(y_labels)),
    yaxis=dict(autorange="reversed"),
    xaxis=dict(side="top"),
    margin=dict(l=200, r=150, t=80, b=80),
    images=layout_images,
)

# --- Write HTML ---
fig.write_html(OUT_HTML, include_plotlyjs="cdn")
print(f"Wrote {OUT_HTML}")
# optional: open in browser if desired
try:
    fig.show()
except Exception:
    pass
